const types = Object.freeze({
    SET_TASKS: "SET_TASKS",
    TOGGLE_LOADING: "TOGGLE_LOADING",
    DELETE_ONE_TASK: "DELETE_ONE_TASK",
    ADD_TASK: "ADD_TASK",
    EDIT_TASK: "EDIT_TASK",
    TOGGLE_CHECK_TASK: "TOGGLE_CHECK_TASK",
    DELETE_CHECKED_TASKS: "DELETE_CHECKED_TASKS",
    TOGGLE_CHECK_ALL_TASKS: "TOGGLE_CHECK_ALL_TASKS",
    TOOGLE_OPEN_ADD_TASK_MODAL: "TOOGLE_OPEN_ADD_TASK_MODAL",
    TOGGLE_OPEN_CONFIRM_MODAL: "TOGGLE_OPEN_CONFIRM_MODAL",
    SET_OR_REMOVE_EDITABLE_TASK: "SET_OR_REMOVE_EDITABLE_TASK",
    SET_ERROR_MESSAGE: "SET_ERROR_MESSAGE",
    SET_SUCCESS_MESSAGE: "SET_SUCCESS_MESSAGE",
    TOGGLE_ACTIVE_TASK: "TOGGLE_ACTIVE_TASK",
    SET_STATUS: "SET_STATUS",
    CHANGE_SEARCH_VALUE:"CHANGE_SEARCH_VALUE",
    SET_SORT_DATE:"SET_SORT_DATE",
    RESET_SEARCH_FORM:"RESET_SEARCH_FORM",
    SET_SINGLE_TASK:"SET_SINGLE_TASK",
    TOGGLE_EDIT_MODAL:"TOGGLE_EDIT_MODAL",
    CHANGE_INPUT_VALUE:"CHANGE_INPUT_VALUE"

});
export default types;