const types = Object.freeze({
    SET_TASKS: "SET_TASKS",
    TOGGLE_LOADING: "TOGGLE_LOADING",
    DELETE_ONE_TASK: "DELETE_ONE_TASK",
    ADD_TASK: "ADD_TASK",
    EDIT_TASK: "EDIT_TASK",
    TOGGLE_CHECK_TASK: "TOGGLE_CHECK_TASK",
    DELETE_CHECKED_TASKS: "DELETE_CHECKED_TASKS",
    TOGGLE_CHECK_ALL_TASKS: "TOGGLE_CHECK_ALL_TASKS",
    TOOGLE_OPEN_ADD_TASK_MODAL: "TOOGLE_OPEN_ADD_TASK_MODAL",
    TOGGLE_OPEN_CONFIRM_MODAL: "TOGGLE_OPEN_CONFIRM_MODAL",
    SET_OR_REMOVE_EDITABLE_TASK: "SET_OR_REMOVE_EDITABLE_TASK",
    SET_ERROR_MESSAGE: "SET_ERROR_MESSAGE",
    SET_SUCCESS_MESSAGE: "SET_SUCCESS_MESSAGE",
    TOGGLE_ACTIVE_TASK: "TOGGLE_ACTIVE_TASK"
});
export default types;